import 'dart:io';

/// Все тексты интерфейса. Язык по умолчанию — язык системы.
class S {
  const S._({
    required this.code,
    required this.titleOff,
    required this.titleOn,
    required this.titleError,
    required this.subOff,
    required this.subError,
    required this.subDisplay,
    required this.subSystem,
    required this.left,
    required this.until,
    required this.whileRunning,
    required this.whileRunningMany,
    required this.download,
    required this.downloadIdle,
    required this.onSchedule,
    required this.nextWindow,
    required this.todayAt,
    required this.tomorrowAt,
    required this.weekdayAt,
    required this.pickProcessFirst,
    required this.notRunning,
    required this.notRunningAny,
    required this.footer,
    required this.minimize,
    required this.hideToTray,
    required this.orbOn,
    required this.orbOff,
    required this.settings,
    required this.hide,
    required this.pageMode,
    required this.pageSchedule,
    required this.pageGeneral,
    required this.pageSystem,
    required this.display,
    required this.displayCanSleep,
    required this.displayStaysOn,
    required this.untilLabel,
    required this.untilAlways,
    required this.untilTimer,
    required this.untilProcess,
    required this.untilDownload,
    required this.minutes,
    required this.hours,
    required this.chooseProcess,
    required this.downloadHint,
    required this.threshold,
    required this.adapterLabel,
    required this.adapterTitle,
    required this.allAdapters,
    required this.allAdaptersHint,
    required this.disconnected,
    required this.kbs,
    required this.mbs,
    required this.back,
    required this.refresh,
    required this.searchProcess,
    required this.nothingFound,
    required this.pickHint,
    required this.picked,
    required this.scheduleToggle,
    required this.days,
    required this.from,
    required this.to,
    required this.overnight,
    required this.color,
    required this.language,
    required this.hotkey,
    required this.hotkeyBusy,
    required this.hotkeyPress,
    required this.hotkeyNeedsModifier,
    required this.autostart,
    required this.sounds,
    required this.updates,
    required this.checkNow,
    required this.checkUpdates,
    required this.updCurrent,
    required this.updChecking,
    required this.updLatest,
    required this.updAvailable,
    required this.updDownloading,
    required this.updInstalling,
    required this.updFailed,
    required this.holdToUpdate,
    required this.holdToDownload,
    required this.accentNames,
    required this.trayOff,
    required this.trayOn,
    required this.trayError,
    required this.trayDisplay,
    required this.trayTurnOn,
    required this.trayTurnOff,
    required this.trayShow,
    required this.trayQuit,
    required this.doneTimer,
    required this.doneProcess,
    required this.doneProcessMany,
    required this.doneDownload,
    required this.doneSchedule,
    required this.toggledOn,
    required this.toggledOff,
  });

  final String code;
  final String titleOff, titleOn, titleError;
  final String subOff, subError, subDisplay, subSystem;
  final String Function(String left, String hhmm) left;
  final String Function(String hhmm) until;
  final String Function(String name) whileRunning;
  final String Function(int count) whileRunningMany;
  final String Function(String speed) download;
  final String Function(String left) downloadIdle;
  final String Function(String hhmm) onSchedule;
  final String Function(String when) nextWindow;
  final String Function(String hhmm) todayAt, tomorrowAt;
  final String Function(int weekday, String hhmm) weekdayAt;
  final String pickProcessFirst;
  final String Function(String name) notRunning;
  final String notRunningAny;
  final String Function(String version) footer;
  final String minimize, hideToTray, orbOn, orbOff, settings, hide;
  final String pageMode, pageSchedule, pageGeneral, pageSystem;
  final String display, displayCanSleep, displayStaysOn;
  final String untilLabel, untilAlways, untilTimer, untilProcess, untilDownload;
  final String minutes, hours;
  final String chooseProcess, kbs, mbs;
  final String Function(String threshold) downloadHint;
  final String threshold, adapterTitle, allAdapters, allAdaptersHint, disconnected;
  final String Function(String name) adapterLabel;
  final String back, refresh, searchProcess, nothingFound, pickHint;
  final String Function(int count, int max) picked;
  final String scheduleToggle;
  final List<String> days;
  final String from, to, overnight;
  final String color, language, hotkey, hotkeyBusy, hotkeyPress, hotkeyNeedsModifier, autostart, sounds;
  final List<String> accentNames;
  final String updates, checkNow, checkUpdates, updChecking, updInstalling, updFailed;
  final String Function(String version) updCurrent, updLatest, updAvailable, holdToUpdate, holdToDownload;
  final String Function(int percent) updDownloading;
  final String trayOff, trayOn, trayError, trayDisplay;
  final String trayTurnOn, trayTurnOff, trayShow, trayQuit;
  final String doneTimer, doneProcessMany, doneDownload, doneSchedule, toggledOn, toggledOff;
  final String Function(String name) doneProcess;

  /// Для теста: все строки (функции вызываются с образцом).
  List<String> get all => [
    titleOff,
    titleOn,
    titleError,
    subOff,
    subError,
    subDisplay,
    subSystem,
    left('1', '2'),
    until('1'),
    whileRunning('x'),
    whileRunningMany(2),
    download('1'),
    downloadIdle('1'),
    onSchedule('1'),
    nextWindow('1'),
    todayAt('1'),
    tomorrowAt('1'),
    for (var d = 1; d <= 7; d++) weekdayAt(d, '1'),
    pickProcessFirst,
    notRunning('x'),
    notRunningAny,
    footer('1'),
    minimize,
    hideToTray,
    orbOn,
    orbOff,
    settings,
    hide,
    pageMode,
    pageSchedule,
    pageGeneral,
    pageSystem,
    display,
    displayCanSleep,
    displayStaysOn,
    untilLabel,
    untilAlways,
    untilTimer,
    untilProcess,
    untilDownload,
    minutes,
    hours,
    chooseProcess,
    downloadHint('1'),
    threshold,
    adapterLabel('x'),
    adapterTitle,
    allAdapters,
    allAdaptersHint,
    disconnected,
    kbs,
    mbs,
    back,
    refresh,
    searchProcess,
    nothingFound,
    pickHint,
    picked(1, 2),
    scheduleToggle,
    ...days,
    from,
    to,
    overnight,
    color,
    language,
    hotkey,
    hotkeyBusy,
    hotkeyPress,
    hotkeyNeedsModifier,
    autostart,
    sounds,
    ...accentNames,
    updates,
    checkNow,
    checkUpdates,
    updCurrent('1'),
    updChecking,
    updLatest('1'),
    updAvailable('1'),
    updDownloading(1),
    updInstalling,
    updFailed,
    holdToUpdate('1'),
    holdToDownload('1'),
    trayOff,
    trayOn,
    trayError,
    trayDisplay,
    trayTurnOn,
    trayTurnOff,
    trayShow,
    trayQuit,
    doneTimer,
    doneProcess('x'),
    doneProcessMany,
    doneDownload,
    doneSchedule,
    toggledOn,
    toggledOff,
  ];

  static final ru = S._(
    code: 'ru',
    titleOff: 'Обычный сон',
    titleOn: 'Не даю уснуть',
    titleError: 'Не получилось',
    subOff: 'Компьютер уснёт по настройкам Windows',
    subError: 'Windows отклонила запрос питания',
    subDisplay: 'Система и экран не уснут',
    subSystem: 'Система не уснёт, экран может погаснуть',
    left: (l, t) => 'ещё $l · до $t',
    until: (t) => ' до $t',
    whileRunning: (n) => 'пока работает $n',
    whileRunningMany: (n) => 'пока работает любая из $n программ',
    download: (v) => 'загрузка идёт · $v',
    downloadIdle: (l) => 'загрузка затихла · выключусь через $l',
    onSchedule: (t) => 'по расписанию до $t',
    nextWindow: (w) => 'Расписание: $w',
    todayAt: (t) => 'сегодня в $t',
    tomorrowAt: (t) => 'завтра в $t',
    weekdayAt: (d, t) =>
        '${const ['в понедельник', 'во вторник', 'в среду', 'в четверг', 'в пятницу', 'в субботу', 'в воскресенье'][d - 1]} в $t',
    pickProcessFirst: 'Сначала выберите процесс в настройках',
    notRunning: (n) => '$n не запущен',
    notRunningAny: 'Ни одна из выбранных программ не запущена',
    footer: (v) => 'v$v · пробел — вкл/выкл · esc — в трей',
    minimize: 'Свернуть',
    hideToTray: 'Спрятать в трей',
    orbOn: 'Включить режим «не спать»',
    orbOff: 'Выключить режим «не спать»',
    settings: 'Настройки',
    hide: 'Скрыть',
    pageMode: 'Режим',
    pageSchedule: 'Расписание',
    pageGeneral: 'Общие',
    pageSystem: 'Система',
    display: 'ЭКРАН',
    displayCanSleep: 'Может гаснуть',
    displayStaysOn: 'Не гаснет',
    untilLabel: 'ДО КАКИХ ПОР',
    untilAlways: 'Всегда',
    untilTimer: 'Таймер',
    untilProcess: 'Процесс',
    untilDownload: 'Загрузка',
    minutes: 'м',
    hours: 'ч',
    chooseProcess: 'Выбрать процесс',
    downloadHint: (t) => 'Выключусь, когда загрузка < $t 2 минуты подряд',
    threshold: 'Порог скорости',
    adapterLabel: (n) => 'Адаптер: $n',
    adapterTitle: 'Сетевой адаптер',
    allAdapters: 'Все',
    allAdaptersHint: 'кроме VPN',
    disconnected: 'не подключён',
    kbs: 'КБ/с',
    mbs: 'МБ/с',
    back: 'Назад',
    refresh: 'Обновить список',
    searchProcess: 'Поиск процесса',
    nothingFound: 'Ничего не нашлось',
    pickHint: 'Можно выбрать несколько программ',
    picked: (n, m) => 'Выбрано $n из $m · не сплю, пока работает любая',
    scheduleToggle: 'Не спать по расписанию',
    days: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
    from: 'С',
    to: 'До',
    overnight: 'через полночь',
    color: 'ЦВЕТ',
    language: 'ЯЗЫК',
    hotkey: 'Горячая клавиша',
    hotkeyBusy: 'занята другой программой',
    hotkeyPress: 'нажмите сочетание · esc — отмена',
    hotkeyNeedsModifier: 'нужен Ctrl, Alt или Win',
    autostart: 'Запуск с Windows',
    sounds: 'Звуки',
    updates: 'ОБНОВЛЕНИЯ',
    checkNow: 'Проверить сейчас',
    checkUpdates: 'Проверять автоматически',
    updCurrent: (v) => 'установлена v$v',
    updChecking: 'проверяю…',
    updLatest: (v) => 'v$v — последняя версия',
    updAvailable: (v) => 'доступна версия $v',
    updDownloading: (p) => 'Скачиваю… $p%',
    updInstalling: 'Запускаю установщик…',
    updFailed: 'не получилось — попробуйте ещё раз',
    holdToUpdate: (v) => 'Удерживайте — обновить до $v',
    holdToDownload: (v) => 'Удерживайте — скачать $v',
    accentNames: ['Лиловый', 'Голубой', 'Бирюзовый', 'Зелёный', 'Персиковый', 'Розовый'],
    trayOff: 'Vigilia — обычный сон',
    trayOn: 'Vigilia — не даю уснуть',
    trayError: 'Vigilia — ошибка запроса питания',
    trayDisplay: ' · экран включён',
    trayTurnOn: 'Включить',
    trayTurnOff: 'Выключить',
    trayShow: 'Показать окно',
    trayQuit: 'Выход',
    doneTimer: 'Таймер истёк — компьютер снова может уснуть',
    doneProcess: (n) => '$n завершился — режим «не спать» выключен',
    doneProcessMany: 'Выбранные программы завершились — режим «не спать» выключен',
    doneDownload: 'Загрузка закончилась — режим «не спать» выключен',
    doneSchedule: 'Окно расписания закончилось — компьютер снова может уснуть',
    toggledOn: 'Режим «не спать» включён',
    toggledOff: 'Режим «не спать» выключен',
  );

  static final en = S._(
    code: 'en',
    titleOff: 'Normal sleep',
    titleOn: 'Keeping awake',
    titleError: 'Something failed',
    subOff: 'Windows will sleep as usual',
    subError: 'Windows rejected the power request',
    subDisplay: 'System and display stay awake',
    subSystem: 'System stays awake, display may turn off',
    left: (l, t) => '$l left · until $t',
    until: (t) => ' until $t',
    whileRunning: (n) => 'while $n is running',
    whileRunningMany: (n) => 'while any of $n programs is running',
    download: (v) => 'downloading · $v',
    downloadIdle: (l) => 'download idle · off in $l',
    onSchedule: (t) => 'on schedule until $t',
    nextWindow: (w) => 'Schedule: $w',
    todayAt: (t) => 'today at $t',
    tomorrowAt: (t) => 'tomorrow at $t',
    weekdayAt: (d, t) =>
        'on ${const ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][d - 1]} at $t',
    pickProcessFirst: 'Choose a process in settings first',
    notRunning: (n) => '$n is not running',
    notRunningAny: 'None of the chosen programs is running',
    footer: (v) => 'v$v · space — on/off · esc — to tray',
    minimize: 'Minimize',
    hideToTray: 'Hide to tray',
    orbOn: 'Turn keep-awake on',
    orbOff: 'Turn keep-awake off',
    settings: 'Settings',
    hide: 'Hide',
    pageMode: 'Mode',
    pageSchedule: 'Schedule',
    pageGeneral: 'General',
    pageSystem: 'System',
    display: 'DISPLAY',
    displayCanSleep: 'May turn off',
    displayStaysOn: 'Stays on',
    untilLabel: 'UNTIL',
    untilAlways: 'Always',
    untilTimer: 'Timer',
    untilProcess: 'Process',
    untilDownload: 'Download',
    minutes: 'm',
    hours: 'h',
    chooseProcess: 'Choose process',
    downloadHint: (t) => 'Turns off after 2 minutes below $t',
    threshold: 'Speed threshold',
    adapterLabel: (n) => 'Adapter: $n',
    adapterTitle: 'Network adapter',
    allAdapters: 'All',
    allAdaptersHint: 'except VPN',
    disconnected: 'disconnected',
    kbs: 'KB/s',
    mbs: 'MB/s',
    back: 'Back',
    refresh: 'Refresh list',
    searchProcess: 'Search process',
    nothingFound: 'Nothing found',
    pickHint: 'You can pick several programs',
    picked: (n, m) => '$n of $m picked · awake while any is running',
    scheduleToggle: 'Stay awake on schedule',
    days: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
    from: 'From',
    to: 'To',
    overnight: 'overnight',
    color: 'COLOR',
    language: 'LANGUAGE',
    hotkey: 'Global hotkey',
    hotkeyBusy: 'taken by another app',
    hotkeyPress: 'press keys · esc — cancel',
    hotkeyNeedsModifier: 'add Ctrl, Alt or Win',
    autostart: 'Start with Windows',
    sounds: 'Sounds',
    updates: 'UPDATES',
    checkNow: 'Check now',
    checkUpdates: 'Check automatically',
    updCurrent: (v) => 'v$v installed',
    updChecking: 'checking…',
    updLatest: (v) => 'v$v is the latest',
    updAvailable: (v) => 'version $v is available',
    updDownloading: (p) => 'Downloading… $p%',
    updInstalling: 'Starting the installer…',
    updFailed: 'failed — please try again',
    holdToUpdate: (v) => 'Hold to update to $v',
    holdToDownload: (v) => 'Hold to download $v',
    accentNames: ['Mauve', 'Blue', 'Teal', 'Green', 'Peach', 'Pink'],
    trayOff: 'Vigilia — normal sleep',
    trayOn: 'Vigilia — keeping awake',
    trayError: 'Vigilia — power request failed',
    trayDisplay: ' · display on',
    trayTurnOn: 'Turn on',
    trayTurnOff: 'Turn off',
    trayShow: 'Show window',
    trayQuit: 'Quit',
    doneTimer: 'Timer is over — the PC may sleep again',
    doneProcess: (n) => '$n has exited — keep-awake is off',
    doneProcessMany: 'The chosen programs have exited — keep-awake is off',
    doneDownload: 'Download finished — keep-awake is off',
    doneSchedule: 'Scheduled window is over — the PC may sleep again',
    toggledOn: 'Keep-awake is on',
    toggledOff: 'Keep-awake is off',
  );

  static S of(String? code) => switch (code ?? systemLanguage()) {
    'ru' => ru,
    _ => en,
  };

  static String systemLanguage() {
    return Platform.localeName.toLowerCase().startsWith('ru') ? 'ru' : 'en';
  }

  /// Текущий язык интерфейса (меняет контроллер).
  static S current = ru;
}
