import 'dart:io';

/// Все тексты интерфейса. Язык по умолчанию — язык системы.
class S {
  const S._({
    required this.code,
    required this.titleOff,
    required this.titleOn,
    required this.titleError,
    required this.subOff,
    required this.subError,
    required this.subDisplay,
    required this.subSystem,
    required this.left,
    required this.until,
    required this.whileRunning,
    required this.download,
    required this.downloadIdle,
    required this.onSchedule,
    required this.pickProcessFirst,
    required this.notRunning,
    required this.footer,
    required this.minimize,
    required this.hideToTray,
    required this.orbOn,
    required this.orbOff,
    required this.settings,
    required this.hide,
    required this.pageMode,
    required this.pageSchedule,
    required this.pageGeneral,
    required this.display,
    required this.displayCanSleep,
    required this.displayStaysOn,
    required this.untilLabel,
    required this.untilAlways,
    required this.untilTimer,
    required this.untilProcess,
    required this.untilDownload,
    required this.minutes,
    required this.hours,
    required this.chooseProcess,
    required this.downloadHint,
    required this.kbs,
    required this.mbs,
    required this.back,
    required this.refresh,
    required this.searchProcess,
    required this.nothingFound,
    required this.scheduleToggle,
    required this.days,
    required this.from,
    required this.to,
    required this.overnight,
    required this.color,
    required this.language,
    required this.hotkey,
    required this.hotkeyBusy,
    required this.autostart,
    required this.sounds,
    required this.accentNames,
    required this.trayOff,
    required this.trayOn,
    required this.trayError,
    required this.trayDisplay,
    required this.trayTurnOn,
    required this.trayTurnOff,
    required this.trayShow,
    required this.trayQuit,
    required this.doneTimer,
    required this.doneProcess,
    required this.doneDownload,
    required this.doneSchedule,
    required this.toggledOn,
    required this.toggledOff,
  });

  final String code;
  final String titleOff, titleOn, titleError;
  final String subOff, subError, subDisplay, subSystem;
  final String Function(String left, String hhmm) left;
  final String Function(String hhmm) until;
  final String Function(String name) whileRunning;
  final String Function(String speed) download;
  final String Function(String left) downloadIdle;
  final String Function(String hhmm) onSchedule;
  final String pickProcessFirst;
  final String Function(String name) notRunning;
  final String Function(String version) footer;
  final String minimize, hideToTray, orbOn, orbOff, settings, hide;
  final String pageMode, pageSchedule, pageGeneral;
  final String display, displayCanSleep, displayStaysOn;
  final String untilLabel, untilAlways, untilTimer, untilProcess, untilDownload;
  final String minutes, hours;
  final String chooseProcess, downloadHint, kbs, mbs;
  final String back, refresh, searchProcess, nothingFound;
  final String scheduleToggle;
  final List<String> days;
  final String from, to, overnight;
  final String color, language, hotkey, hotkeyBusy, autostart, sounds;
  final List<String> accentNames;
  final String trayOff, trayOn, trayError, trayDisplay;
  final String trayTurnOn, trayTurnOff, trayShow, trayQuit;
  final String doneTimer, doneDownload, doneSchedule, toggledOn, toggledOff;
  final String Function(String name) doneProcess;

  /// Для теста: все строки (функции вызываются с образцом).
  List<String> get all => [
    titleOff,
    titleOn,
    titleError,
    subOff,
    subError,
    subDisplay,
    subSystem,
    left('1', '2'),
    until('1'),
    whileRunning('x'),
    download('1'),
    downloadIdle('1'),
    onSchedule('1'),
    pickProcessFirst,
    notRunning('x'),
    footer('1'),
    minimize,
    hideToTray,
    orbOn,
    orbOff,
    settings,
    hide,
    pageMode,
    pageSchedule,
    pageGeneral,
    display,
    displayCanSleep,
    displayStaysOn,
    untilLabel,
    untilAlways,
    untilTimer,
    untilProcess,
    untilDownload,
    minutes,
    hours,
    chooseProcess,
    downloadHint,
    kbs,
    mbs,
    back,
    refresh,
    searchProcess,
    nothingFound,
    scheduleToggle,
    ...days,
    from,
    to,
    overnight,
    color,
    language,
    hotkey,
    hotkeyBusy,
    autostart,
    sounds,
    ...accentNames,
    trayOff,
    trayOn,
    trayError,
    trayDisplay,
    trayTurnOn,
    trayTurnOff,
    trayShow,
    trayQuit,
    doneTimer,
    doneProcess('x'),
    doneDownload,
    doneSchedule,
    toggledOn,
    toggledOff,
  ];

  static final ru = S._(
    code: 'ru',
    titleOff: 'Обычный сон',
    titleOn: 'Не даю уснуть',
    titleError: 'Не получилось',
    subOff: 'Компьютер уснёт по настройкам Windows',
    subError: 'Windows отклонила запрос питания',
    subDisplay: 'Система и экран не уснут',
    subSystem: 'Система не уснёт, экран может погаснуть',
    left: (l, t) => 'ещё $l · до $t',
    until: (t) => ' до $t',
    whileRunning: (n) => 'пока работает $n',
    download: (v) => 'загрузка идёт · $v',
    downloadIdle: (l) => 'загрузка затихла · выключусь через $l',
    onSchedule: (t) => 'по расписанию до $t',
    pickProcessFirst: 'Сначала выберите процесс в настройках',
    notRunning: (n) => '$n не запущен',
    footer: (v) => 'v$v · пробел — вкл/выкл · esc — в трей',
    minimize: 'Свернуть',
    hideToTray: 'Спрятать в трей',
    orbOn: 'Включить режим «не спать»',
    orbOff: 'Выключить режим «не спать»',
    settings: 'Настройки',
    hide: 'Скрыть',
    pageMode: 'Режим',
    pageSchedule: 'Расписание',
    pageGeneral: 'Общие',
    display: 'ЭКРАН',
    displayCanSleep: 'Может гаснуть',
    displayStaysOn: 'Не гаснет',
    untilLabel: 'ДО КАКИХ ПОР',
    untilAlways: 'Всегда',
    untilTimer: 'Таймер',
    untilProcess: 'Процесс',
    untilDownload: 'Загрузка',
    minutes: 'м',
    hours: 'ч',
    chooseProcess: 'Выбрать процесс',
    downloadHint: 'Выключусь, когда загрузка < 100 КБ/с 2 минуты подряд',
    kbs: 'КБ/с',
    mbs: 'МБ/с',
    back: 'Назад',
    refresh: 'Обновить список',
    searchProcess: 'Поиск процесса',
    nothingFound: 'Ничего не нашлось',
    scheduleToggle: 'Не спать по расписанию',
    days: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
    from: 'С',
    to: 'До',
    overnight: 'через полночь',
    color: 'ЦВЕТ',
    language: 'ЯЗЫК',
    hotkey: 'Горячая клавиша',
    hotkeyBusy: 'занята другой программой',
    autostart: 'Запуск с Windows',
    sounds: 'Звуки',
    accentNames: ['Лиловый', 'Голубой', 'Бирюзовый', 'Зелёный', 'Персиковый', 'Розовый'],
    trayOff: 'Vigilia — обычный сон',
    trayOn: 'Vigilia — не даю уснуть',
    trayError: 'Vigilia — ошибка запроса питания',
    trayDisplay: ' · экран включён',
    trayTurnOn: 'Включить',
    trayTurnOff: 'Выключить',
    trayShow: 'Показать окно',
    trayQuit: 'Выход',
    doneTimer: 'Таймер истёк — компьютер снова может уснуть',
    doneProcess: (n) => '$n завершился — режим «не спать» выключен',
    doneDownload: 'Загрузка закончилась — режим «не спать» выключен',
    doneSchedule: 'Окно расписания закончилось — компьютер снова может уснуть',
    toggledOn: 'Режим «не спать» включён',
    toggledOff: 'Режим «не спать» выключен',
  );

  static final en = S._(
    code: 'en',
    titleOff: 'Normal sleep',
    titleOn: 'Keeping awake',
    titleError: 'Something failed',
    subOff: 'Windows will sleep as usual',
    subError: 'Windows rejected the power request',
    subDisplay: 'System and display stay awake',
    subSystem: 'System stays awake, display may turn off',
    left: (l, t) => '$l left · until $t',
    until: (t) => ' until $t',
    whileRunning: (n) => 'while $n is running',
    download: (v) => 'downloading · $v',
    downloadIdle: (l) => 'download idle · off in $l',
    onSchedule: (t) => 'on schedule until $t',
    pickProcessFirst: 'Choose a process in settings first',
    notRunning: (n) => '$n is not running',
    footer: (v) => 'v$v · space — on/off · esc — to tray',
    minimize: 'Minimize',
    hideToTray: 'Hide to tray',
    orbOn: 'Turn keep-awake on',
    orbOff: 'Turn keep-awake off',
    settings: 'Settings',
    hide: 'Hide',
    pageMode: 'Mode',
    pageSchedule: 'Schedule',
    pageGeneral: 'General',
    display: 'DISPLAY',
    displayCanSleep: 'May turn off',
    displayStaysOn: 'Stays on',
    untilLabel: 'UNTIL',
    untilAlways: 'Always',
    untilTimer: 'Timer',
    untilProcess: 'Process',
    untilDownload: 'Download',
    minutes: 'm',
    hours: 'h',
    chooseProcess: 'Choose process',
    downloadHint: 'Turns off after 2 minutes below 100 KB/s',
    kbs: 'KB/s',
    mbs: 'MB/s',
    back: 'Back',
    refresh: 'Refresh list',
    searchProcess: 'Search process',
    nothingFound: 'Nothing found',
    scheduleToggle: 'Stay awake on schedule',
    days: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
    from: 'From',
    to: 'To',
    overnight: 'overnight',
    color: 'COLOR',
    language: 'LANGUAGE',
    hotkey: 'Global hotkey',
    hotkeyBusy: 'taken by another app',
    autostart: 'Start with Windows',
    sounds: 'Sounds',
    accentNames: ['Mauve', 'Blue', 'Teal', 'Green', 'Peach', 'Pink'],
    trayOff: 'Vigilia — normal sleep',
    trayOn: 'Vigilia — keeping awake',
    trayError: 'Vigilia — power request failed',
    trayDisplay: ' · display on',
    trayTurnOn: 'Turn on',
    trayTurnOff: 'Turn off',
    trayShow: 'Show window',
    trayQuit: 'Quit',
    doneTimer: 'Timer is over — the PC may sleep again',
    doneProcess: (n) => '$n has exited — keep-awake is off',
    doneDownload: 'Download finished — keep-awake is off',
    doneSchedule: 'Scheduled window is over — the PC may sleep again',
    toggledOn: 'Keep-awake is on',
    toggledOff: 'Keep-awake is off',
  );

  static S of(String? code) => switch (code ?? systemLanguage()) {
    'ru' => ru,
    _ => en,
  };

  static String systemLanguage() {
    return Platform.localeName.toLowerCase().startsWith('ru') ? 'ru' : 'en';
  }

  /// Текущий язык интерфейса (меняет контроллер).
  static S current = ru;
}
